config/routes.rb
RailsCanvas::Application.routes.draw do

  get "home/index"
  get "home/salesforce", as: :salesforce
  match "canvas" => "canvas#index", :via => :post

  root 'home#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/canvas_controller.rb
class CanvasController < ApplicationController

  # bypass request forgery protection for salesforce
  protect_from_forgery except: :index

  def index
    # store all of the signed request data returned
    # by salesforce in the current user's session
  	session[:signed_request] = Restforce.decode_signed_request(params[:signed_request], 
      ENV['CLIENT_SECRET'])

    redirect_to :root
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    client = Restforce.new(
        oauth_token: session['signed_request']['client']['oauthToken'],
        instance_url: session['signed_request']['client']['instanceUrl']
      )  	
  	@contacts = client.query("select Id, Name from Contact Limit 10")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/canvas_helper.rb
module CanvasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>List of Contacts</h1>

<% @contacts.each do |c| %>
	<%= c.Name %><br>
<% end %>

<p>Here's the <%= link_to 'signed request info', salesforce_path %>.</p>

app/views/home/salesforce.html.erb
<h1>Salesforce Signed Request Info</h1>

<h2>UserId</h2>

<%= session['signed_request']['userId'] %>

<h2>Client</h2>

<%= session['signed_request']['client'] %>

<h2>Context</h2>

<%= session['signed_request']['context'] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCanvas</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>